### ISSUE TITLE
Support for Animalia

### ISSUE THREAD

**Issue by HeyITGuyFixIt** [sfence/skeletons#1]
Would be neat to have support for ElCeejo's Animalia mod.

**Comment by sfence** [comment]
I don`t have models of skeletons for bat, bird, fox, frog, owl, reindeer, tropical fish, turkey and wolf. 

Are you willing to help me with that models? I use to make them in minetest in ratio 16:1, save them like world edit schematic and convert them into nodebox. So if you will be able to create for me world edit schematics of size 16x16x16 or more or animals bigger then one node, it will be really helpful.

**Comment by HeyITGuyFixIt** [comment]
I wish I could. I don't have any experience with creating models.

**Comment by sfence** [comment]
Animalia should be supported with commit 3a6cde508c079896ab1478443b35a7b4214b3347 / tag 0.8.0.
